title: "Xingyuan Zhao"
description: "Minimalist Jekyll-based personal academic website with blogs"
baseurl: ""
url: ""
author: "Xingyuan Zhao"
email: "xingyuan.zhao5@gmail.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
google_analytics:

social:
#   # - icon: fa fa-twitter
#     # link: "https://twitter.com/YuLiangcheng"
  - icon: fa fa-github
    link: "https://github.com/yukiyakiZ"
  - icon: fa fa-envelope
    link: "mailto:xingyuan.zhao5@gmail.com"
  # better google scholar icon with Academicons
#   # - icon: fa fa-google
#     # link: "https://scholar.google.com/citations?hl=en&user=ZAK8IpYAAAAJ"
#   - icon: ai ai-google-scholar
#     link: "https://scholar.google.com/citations?hl=en&user=ZAK8IpYAAAAJ"  
#   - icon: fa fa-linkedin
#     link: "https://www.linkedin.com/in/liangcheng-yu-5b1a41a3/"    
#   - icon: fa fa-file-pdf-o
#     link: /doc/cv/cv.pdf
#   - icon: fa fa-key
#     link: "https://keybase.io/liangcheng_yu?refresh=faf3b#panel-actions-profile"

plugins:
  - jekyll-sitemap

exclude: [CNAME", "Gemfile", "Makefile"]
